apiVersion: v1
kind: Service
metadata:
  name: telemetry
  namespace: smartdom
  labels:
    app: telemetry
spec:
  type: ClusterIP
  selector:
    app: telemetry
  ports:
    - name: http
      port: 80
      targetPort: 8080
