apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry
  namespace: smartdom
  labels:
    app: telemetry
    org.bstu.course: RSIOT
    org.bstu.variant: "0"
  annotations:
    org.bstu.student.slug: "00000-v0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: telemetry
    spec:
      containers:
        - name: api
          image: smartdom-telemetry:0.1.0
          imagePullPolicy: IfNotPresent # образ загружен через kind load
          ports:
            - containerPort: 8080
          env:
            - name: STU_ID
              value: "00000"
            - name: STU_VARIANT
              value: "0"
            - name: ALERT_THRESHOLD_C
              valueFrom:
                configMapKeyRef:
                  name: telemetry-config
                  key: ALERT_THRESHOLD_C
            - name: WARMUP_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: telemetry-config
                  key: WARMUP_SECONDS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: telemetry-secret
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 3"]
      terminationGracePeriodSeconds: 30
