apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    org.bstu.course: RSIOT
    org.bstu.variant: {{ .Values.student.variant | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: STU_ID
              value: {{ .Values.student.id | quote }}
            - name: STU_VARIANT
              value: {{ .Values.student.variant | quote }}
          readinessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 3
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
